// Local-only bootstrap. No hosted targets, plaintext SQL credentials or shell interpolation.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { parseEnv } from "node:util";
import { randomBytes, randomInt } from "node:crypto";
import { execFileSync } from "node:child_process";
import { createClient } from "@supabase/supabase-js";
import { hashPin, verifyPin } from "../lib/auth/pin.ts";

const root = fileURLToPath(new URL("../", import.meta.url));
const container = "supabase_db_digital-queue-management-system";
const org = "10000000-0000-4000-8000-000000000001", loc = "20000000-0000-4000-8000-000000000001";
const staffId = "40000000-0000-4000-8000-000000000001";
const email = "demo-manager@queue.example.test", staffCode = "DEMO_KOKKOLA";
let stage = "checking local runtime";
class SetupError extends Error {}
function requireLocal(value) {
  let url; try { url = new URL(value); } catch { throw new SetupError("Invalid local Supabase URL."); }
  if (url.protocol !== "http:" || !["127.0.0.1", "localhost", "[::1]"].includes(url.hostname) || url.username || url.password || url.pathname !== "/") throw new SetupError("Refusing a non-local Supabase target.");
}
function cli(...args) {
  if (!process.env.npm_execpath) throw new SetupError("Run through npm run local:setup (Node 24) or the documented npm exec command.");
  return execFileSync(process.execPath, [process.env.npm_execpath, "exec", "--yes", "--package=supabase@2.117.0", "--", "supabase", ...args], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
}
function sql(statement) {
  return execFileSync("docker", ["exec", "-i", container, "psql", "-X", "-qAt", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1"], { input: statement, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim();
}
const literal = (value) => `'${String(value).replaceAll("'", "''")}'`;
function saveEnv(path, previous, updates) {
  // Preserve unrelated settings/comments while replacing every managed key once.
  const lines = previous.split(/\r?\n/).filter((line) => !Object.keys(updates).some((key) => new RegExp(`^\\s*(?:export\\s+)?${key}\\s*=`).test(line)));
  writeFileSync(path, `${lines.join("\n").trimEnd()}\n${Object.entries(updates).map(([key, value]) => `${key}=${JSON.stringify(value)}`).join("\n")}\n`, { mode: 0o600 });
}
try {
  if (Number(process.versions.node.split(".")[0]) !== 24) throw new SetupError("Use Node.js 24 as specified in .nvmrc.");
  const cfg = JSON.parse(cli("status", "-o", "json"));
  requireLocal(cfg.API_URL);
  if (!cfg.PUBLISHABLE_KEY?.startsWith("sb_publishable_") || !cfg.SERVICE_ROLE_KEY) throw new SetupError("Current local publishable/service-role keys are unavailable; start Supabase with CLI 2.117.0.");
  const envPath = resolve(root, ".env.local"), demoPath = resolve(root, ".env.demo.local");
  const previous = existsSync(envPath) ? readFileSync(envPath, "utf8") : "# Local development only. Generated by npm run local:setup. Never commit.\n";
  const env = parseEnv(previous);
  if (env.NEXT_PUBLIC_SUPABASE_URL) requireLocal(env.NEXT_PUBLIC_SUPABASE_URL);
  let demo = existsSync(demoPath) ? parseEnv(readFileSync(demoPath, "utf8")) : null;
  if (demo && (demo.SUPABASE_URL !== cfg.API_URL || demo.MANAGER_EMAIL !== email || demo.STAFF_ID !== staffCode || !demo.MANAGER_PASSWORD || !/^\d{6}$/.test(demo.STAFF_PIN ?? ""))) throw new SetupError("Existing .env.demo.local does not match this local setup; preserve it and inspect before proceeding.");
  stage = "applying local migrations and seed";
  cli("migration", "up", "--local");
  sql(readFileSync(resolve(root, "supabase/seed.sql"), "utf8"));
  if (sql(`select count(*) from public.locations where id='${loc}' and organization_id='${org}' and slug='kokkola-health-centre' and active;`) !== "1" || sql(`select count(*) from public.services where organization_id='${org}' and location_id='${loc}' and active;`) === "0") throw new SetupError("Demo location/services are inactive or were changed. Restore them through manager administration before using this setup.");
  const existingUser = sql(`select id from auth.users where lower(email)=${literal(email)};`);
  const existingStaff = sql(`select coalesce(jsonb_agg(jsonb_build_object('id',id,'organizationId',organization_id,'pinHash',pin_hash,'active',active)),'[]'::jsonb) from public.staff where id='${staffId}' or staff_code='${staffCode}';`);
  const staff = JSON.parse(existingStaff);
  if (!demo && (existingUser || staff.length)) throw new SetupError("Demo accounts already exist but .env.demo.local is missing. Refusing to reset existing credentials; recover that local file or reset intentionally through trusted admin tools.");
  if (existingUser && sql(`select count(*) from public.managers where user_id='${existingUser}' and organization_id<>'${org}';`) !== "0") throw new SetupError("Demo manager belongs to another organization; refusing to change membership.");
  if (staff.length && (staff.length !== 1 || staff[0].id !== staffId || staff[0].organizationId !== org || !staff[0].active)) throw new SetupError("Demo Staff ID conflicts or is disabled; inspect it through manager administration.");
  demo ??= { SUPABASE_URL: cfg.API_URL, MANAGER_EMAIL: email, MANAGER_PASSWORD: randomBytes(24).toString("base64url"), STAFF_ID: staffCode, STAFF_PIN: String(randomInt(0, 1000000)).padStart(6) };
  if (staff.length && !await verifyPin(demo.STAFF_PIN, staff[0].pinHash)) throw new SetupError("Stored local demo PIN no longer matches. Refusing to reset staff credentials silently.");
  // Save first so an interrupted bootstrap can resume with the same credentials.
  if (!existsSync(demoPath)) saveEnv(demoPath, "# LOCAL DEMO CREDENTIALS ONLY. Ignored by Git; never use for production.\n", demo);
  stage = "provisioning local demo accounts";
  const admin = createClient(cfg.API_URL, cfg.SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
  let userId = existingUser;
  if (!userId) {
    const { data, error } = await admin.auth.admin.createUser({ email, password: demo.MANAGER_PASSWORD, email_confirm: true });
    if (error || !data.user) throw new SetupError("Could not create the local demo manager. No credential values were logged.");
    userId = data.user.id;
  }
  const auth = createClient(cfg.API_URL, cfg.PUBLISHABLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
  const verified = await auth.auth.signInWithPassword({ email, password: demo.MANAGER_PASSWORD });
  if (verified.error) throw new SetupError("Local demo manager password no longer matches .env.demo.local; refusing to reset it silently.");
  await auth.auth.signOut();
  const encoded = staff.length ? null : await hashPin(demo.STAFF_PIN);
  sql(`begin;
    insert into public.managers(user_id,organization_id,name) values ('${userId}','${org}','Demo manager') on conflict (user_id) do nothing;
    ${encoded ? `insert into public.staff(id,organization_id,name,staff_code,pin_hash) values ('${staffId}','${org}','Demo staff','${staffCode}',${literal(encoded)});` : ""}
    insert into public.staff_assignments(organization_id,staff_id,location_id,service_id)
      select organization_id,'${staffId}',location_id,id from public.services where organization_id='${org}' and location_id='${loc}' and active on conflict (staff_id,service_id) do nothing;
    commit;`);
  stage = "writing local application configuration";
  saveEnv(envPath, previous, {
    NEXT_PUBLIC_SUPABASE_URL: cfg.API_URL, NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: cfg.PUBLISHABLE_KEY,
    SUPABASE_SERVICE_ROLE_KEY: cfg.SERVICE_ROLE_KEY, APP_ORIGIN: "http://localhost:3000",
    AUTH_RATE_LIMIT_SECRET: env.AUTH_RATE_LIMIT_SECRET?.length >= 32 ? env.AUTH_RATE_LIMIT_SECRET : randomBytes(32).toString("hex"),
  });
  const { data, error } = await admin.rpc("get_public_queue_location", { p_slug: "kokkola-health-centre" });
  if (error || !data?.services?.length) throw new SetupError("Local public-location RPC check failed; inspect development diagnostics.");
  console.log("Local migrations/seed verified; public location RPC passed.");
  console.log(".env.local now matches current local Supabase. Restart Next.js with Node 24.");
  console.log("Demo manager and staff are ready. View local-only credentials with: Get-Content .env.demo.local");
  console.log("Customer: http://localhost:3000/q/kokkola-health-centre");
} catch (error) {
  // Child-process and SDK errors can contain secrets. Never dump their objects.
  console.error(error instanceof SetupError ? error.message : `Local setup failed while ${stage}. Check Docker/local Supabase; sensitive details were omitted.`);
  process.exitCode = 1;
}
